Fixes for mounting and matplotlib problems
microsoft/InnerEye-DeepLearning pull request #515
Opened 2021-06-28 10:55 UTC by ant0nsc

- Fix for occasional issues in dataset mounting
- Fix for matplotlib problems on some machines
Closes #513 
Closes #510 

Please follow the guidelines for PRs contained [here](docs/pull_requests.md). Checklist:

- [ ] Ensure that your PR is small, and implements one change.
- [ ] Add unit tests for all functions that you introduced or modified.
- [ ] Run PyCharm's code cleanup tools on your Python files.
- [ ] Link the correct GitHub issue for tracking.
- [ ] Update the [Changelog](CHANGELOG.md) file: Describe your change in terms of 
Added/Changed/Removed/... in the "Upcoming" section.
- [ ] When merging your PR, replace the default merge message with a description of your PR,
and if needed a motivation why that change was required.

2021-06-28 22:18 UTC, ant0nsc commented
This PR should not yet be merged, a first PR build failed in the dataset mounting.

2021-06-30 08:29 UTC, dumbledad requested changes

2021-06-30 08:29 UTC, dumbledad commented on Tests/AfterTraining/test_after_training.py
> -@pytest.mark.skip("Test times out for unknown reasons.")
Do we have an issue to reinvestigate this at a later date?

2021-06-30 08:33 UTC, Shruthi42 approved these changes

2021-06-30 08:41 UTC, JonathanTripp approved these changes

2021-06-30 08:42 UTC, dumbledad commented on Tests/AfterTraining/test_after_training.py
> -@pytest.mark.skip("Test times out for unknown reasons.")
Ah, you are putting it back

2021-06-30 08:42 UTC, dumbledad approved these changes

2021-07-15 09:29 UTC, JonathanTripp approved these changes

2021-07-15 10:36 UTC, dumbledad approved these changes
Looks good

2021-07-15 10:41 UTC, merged